require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/bundle
Style/Documentation:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Metrics/MethodLength:
  ExcludedMethods: [holidays]
  Exclude:
    - db/migrate/*
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - db/schema.rb
Naming/VariableNumber:
  EnforcedStyle: snake_case
  Exclude:
    - config/initializers/simple_form.rb
Rails/LexicallyScopedActionFilter:
  Exclude:
    - app/controllers/concerns/*
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/Capybara/FeatureMethods:
  EnabledMethods: [feature, scenario]
