require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'bin/bundle'
Style/Documentation:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
